Renamed to smuggler2

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,6 +1,6 @@
 # This Travis job script has been generated by a script via
 #
-#   haskell-ci 'travis' 'smuggler.cabal' '--hlint' '--ghc-head' '--no-benchmarks' '--allow-failures=<=8.6.5' '--output' '.travis.yml'
+#   haskell-ci 'travis' 'smuggler2.cabal' '--hlint' '--ghc-head' '--no-benchmarks' '--allow-failures=<=8.6.5' '--output' '.travis.yml'
 #
 # To regenerate the script (for example after adjusting tested-with) run
 #
@@ -113,10 +113,10 @@ install:
   - touch cabal.project
   - |
     echo "packages: ." >> cabal.project
-  - echo 'package smuggler' >> cabal.project
+  - echo 'package smuggler2' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(smuggler)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(smuggler2)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "./configure.ac" ]; then (cd "." && autoreconf -i); fi
@@ -134,16 +134,16 @@ script:
   - cd ${DISTDIR} || false
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
-  - PKGDIR_smuggler="$(find . -maxdepth 1 -type d -regex '.*/smuggler-[0-9.]*')"
+  - PKGDIR_smuggler2="$(find . -maxdepth 1 -type d -regex '.*/smuggler2-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
-    echo "packages: ${PKGDIR_smuggler}" >> cabal.project
-  - echo 'package smuggler' >> cabal.project
+    echo "packages: ${PKGDIR_smuggler2}" >> cabal.project
+  - echo 'package smuggler2' >> cabal.project
   - "echo '  ghc-options: -Werror=missing-methods' >> cabal.project"
   - |
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(smuggler)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(smuggler2)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building...
@@ -155,15 +155,15 @@ script:
   # Testing...
   - ${CABAL} v2-test $WITHCOMPILER ${TEST} ${BENCH} all
   # HLint..
-  - if [ $HCNUMVER -ge 81000 ] && [ $HCNUMVER -lt 81002 ] ; then (cd ${PKGDIR_smuggler} && hlint -XDeriveGeneric -XGeneralizedNewtypeDeriving -XInstanceSigs -XLambdaCase -XOverloadedStrings -XRecordWildCards -XScopedTypeVariables -XStandaloneDeriving -XTypeApplications src) ; fi
-  - if [ $HCNUMVER -ge 81000 ] && [ $HCNUMVER -lt 81002 ] ; then (cd ${PKGDIR_smuggler} && hlint -XDeriveGeneric -XGeneralizedNewtypeDeriving -XInstanceSigs -XLambdaCase -XOverloadedStrings -XRecordWildCards -XScopedTypeVariables -XStandaloneDeriving -XTypeApplications app) ; fi
+  - if [ $HCNUMVER -ge 81000 ] && [ $HCNUMVER -lt 81002 ] ; then (cd ${PKGDIR_smuggler2} && hlint -XDeriveGeneric -XGeneralizedNewtypeDeriving -XInstanceSigs -XLambdaCase -XOverloadedStrings -XRecordWildCards -XScopedTypeVariables -XStandaloneDeriving -XTypeApplications src) ; fi
+  - if [ $HCNUMVER -ge 81000 ] && [ $HCNUMVER -lt 81002 ] ; then (cd ${PKGDIR_smuggler2} && hlint -XDeriveGeneric -XGeneralizedNewtypeDeriving -XInstanceSigs -XLambdaCase -XOverloadedStrings -XRecordWildCards -XScopedTypeVariables -XStandaloneDeriving -XTypeApplications app) ; fi
   # cabal check...
-  - (cd ${PKGDIR_smuggler} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_smuggler2} && ${CABAL} -vnormal check)
   # haddock...
   - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all
   # Building without installed constraints for packages in global-db...
   - rm -f cabal.project.local
   - ${CABAL} v2-build $WITHCOMPILER --disable-tests --disable-benchmarks all
 
-# REGENDATA ("0.10.1",["travis","smuggler.cabal","--hlint","--ghc-head","--no-benchmarks","--allow-failures=<=8.6.5","--output",".travis.yml"])
+# REGENDATA ("0.10.1",["travis","smuggler2.cabal","--hlint","--ghc-head","--no-benchmarks","--allow-failures=<=8.6.5","--output",".travis.yml"])
 # EOF
